<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    public function run()
    {
        $driver = DB::connection()->getDriverName();

        if ($driver === 'mysql') {
            DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        } elseif ($driver === 'sqlite') {
            DB::statement('PRAGMA foreign_keys = OFF;');
        }

        DB::table('books')->truncate();

        if ($driver === 'mysql') {
            DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        } elseif ($driver === 'sqlite') {
            DB::statement('PRAGMA foreign_keys = ON;');
        }

        $books = [
            [
                'title' => 'Atomic Habits',
                'author' => 'James Clear',
                'category' => 'Bisnis',
                'publisher' => 'Penguin',
                'publication_year' => '2018',
                'isbn' => '9780735211292',
                'stock' => 10,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg',
                'synopsis' => 'Cara membangun kebiasaan baik dan membuang kebiasaan buruk.',
            ],
            [
                'title' => 'Psychology of Money',
                'author' => 'Morgan Housel',
                'category' => 'Bisnis',
                'publisher' => 'Harriman House',
                'publication_year' => '2020',
                'isbn' => '9780857197689',
                'stock' => 8,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg',
                'synopsis' => 'Pelajaran abadi mengenai kekayaan, ketamakan, dan kebahagiaan.',
            ],
            [
                'title' => 'Rich Dad Poor Dad',
                'author' => 'Robert Kiyosaki',
                'category' => 'Bisnis',
                'publisher' => 'Plata Publishing',
                'publication_year' => '1997',
                'isbn' => '9781612680194',
                'stock' => 12,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg',
                'synopsis' => 'Apa yang diajarkan orang kaya pada anak-anak mereka tentang uang.',
            ],
            [
                'title' => 'Zero to One',
                'author' => 'Peter Thiel',
                'category' => 'Bisnis',
                'publisher' => 'Crown Business',
                'publication_year' => '2014',
                'isbn' => '9780804139298',
                'stock' => 5,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780804139298-L.jpg',
                'synopsis' => 'Catatan tentang startup, atau bagaimana membangun masa depan.',
            ],
            [
                'title' => 'Start with Why',
                'author' => 'Simon Sinek',
                'category' => 'Bisnis',
                'publisher' => 'Portfolio',
                'publication_year' => '2009',
                'isbn' => '9781591846444',
                'stock' => 7,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9781591846444-L.jpg',
                'synopsis' => 'Bagaimana para pemimpin besar menginspirasi orang lain untuk bertindak.',
            ],
            [
                'title' => 'Thinking, Fast and Slow',
                'author' => 'Daniel Kahneman',
                'category' => 'Bisnis',
                'publisher' => 'Farrar, Straus and Giroux',
                'publication_year' => '2011',
                'isbn' => '9780374275631',
                'stock' => 6,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780374275631-L.jpg',
                'synopsis' => 'Analisis mendalam tentang dua sistem cara berpikir manusia.',
            ],
            [
                'title' => 'Shoe Dog',
                'author' => 'Phil Knight',
                'category' => 'Bisnis',
                'publisher' => 'Scribner',
                'publication_year' => '2016',
                'isbn' => '9781501135910',
                'stock' => 7,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9781501135910-L.jpg',
                'synopsis' => 'Memoar oleh pencipta Nike yang menceritakan kisah di balik logo swoosh.',
            ],
            [
                'title' => 'The Lean Startup',
                'author' => 'Eric Ries',
                'category' => 'Bisnis',
                'publisher' => 'Crown Currency',
                'publication_year' => '2011',
                'isbn' => '9780307887894',
                'stock' => 9,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg',
                'synopsis' => 'Bagaimana pengusaha masa kini menggunakan inovasi berkelanjutan untuk menciptakan bisnis yang sukses.',
            ],

            [
                'title' => 'Clean Code',
                'author' => 'Robert C. Martin',
                'category' => 'Teknologi',
                'publisher' => 'Prentice Hall',
                'publication_year' => '2008',
                'isbn' => '9780132350884',
                'stock' => 15,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg',
                'synopsis' => 'Panduan wajib bagi setiap programmer untuk menulis kode yang rapi.',
            ],
            [
                'title' => 'The Pragmatic Programmer',
                'author' => 'Andrew Hunt',
                'category' => 'Teknologi',
                'publisher' => 'Addison-Wesley',
                'publication_year' => '1999',
                'isbn' => '9780201616224',
                'stock' => 8,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780201616224-L.jpg',
                'synopsis' => 'Perjalanan dari tukang koding menjadi ahli perangkat lunak.',
            ],
            [
                'title' => 'Steve Jobs',
                'author' => 'Walter Isaacson',
                'category' => 'Teknologi',
                'publisher' => 'Simon & Schuster',
                'publication_year' => '2011',
                'isbn' => '9781451648539',
                'stock' => 5,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9781451648539-L.jpg',
                'synopsis' => 'Biografi eksklusif dari pendiri Apple yang visioner.',
            ],
            [
                'title' => 'Eloquent JavaScript',
                'author' => 'Marijn Haverbeke',
                'category' => 'Teknologi',
                'publisher' => 'No Starch Press',
                'publication_year' => '2018',
                'isbn' => '9781593279509',
                'stock' => 10,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9781593279509-L.jpg',
                'synopsis' => 'Menyelami bahasa pemrograman JavaScript secara modern.',
            ],
            [
                'title' => 'The Innovators',
                'author' => 'Walter Isaacson',
                'category' => 'Teknologi',
                'publisher' => 'Simon & Schuster',
                'publication_year' => '2014',
                'isbn' => '9781476708690',
                'stock' => 4,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9781476708690-L.jpg',
                'synopsis' => 'Bagaimana sekelompok hacker, jenius, dan geek menciptakan revolusi digital.',
            ],
            [
                'title' => 'Life 3.0',
                'author' => 'Max Tegmark',
                'category' => 'Teknologi',
                'publisher' => 'Knopf',
                'publication_year' => '2017',
                'isbn' => '9781101946596',
                'stock' => 6,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9781101946596-L.jpg',
                'synopsis' => 'Menjadi manusia di era kecerdasan buatan (AI).',
            ],
            [
                'title' => 'Introduction to Algorithms',
                'author' => 'Thomas H. Cormen',
                'category' => 'Teknologi',
                'publisher' => 'MIT Press',
                'publication_year' => '2009',
                'isbn' => '9780262033848',
                'stock' => 3,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780262033848-L.jpg',
                'synopsis' => 'Buku teks standar algoritma yang mendalam.',
            ],
            [
                'title' => 'Design Patterns',
                'author' => 'Erich Gamma',
                'category' => 'Teknologi',
                'publisher' => 'Addison-Wesley',
                'publication_year' => '1994',
                'isbn' => '9780201633610',
                'stock' => 4,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780201633610-L.jpg',
                'synopsis' => 'Solusi reusable untuk masalah umum dalam desain software.',
            ],
            [
                'title' => 'Refactoring',
                'author' => 'Martin Fowler',
                'category' => 'Teknologi',
                'publisher' => 'Addison-Wesley',
                'publication_year' => '1999',
                'isbn' => '9780201485677',
                'stock' => 5,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780201485677-L.jpg',
                'synopsis' => 'Meningkatkan desain kode yang sudah ada tanpa mengubah perilakunya.',
            ],

            [
                'title' => 'Harry Potter and the Sorcerer\'s Stone',
                'author' => 'J.K. Rowling',
                'category' => 'Fiksi',
                'publisher' => 'Bloomsbury',
                'publication_year' => '1997',
                'isbn' => '9780747532743',
                'stock' => 20,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780747532743-L.jpg',
                'synopsis' => 'Awal mula petualangan Harry di Hogwarts.',
            ],
            [
                'title' => 'Percy Jackson & The Lightning Thief',
                'author' => 'Rick Riordan',
                'category' => 'Fiksi',
                'publisher' => 'Disney Hyperion',
                'publication_year' => '2005',
                'isbn' => '9780786856299',
                'stock' => 12,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780786856299-L.jpg',
                'synopsis' => 'Petualangan seorang demigod modern yang dituduh mencuri petir Zeus.',
            ],
            [
                'title' => 'The Alchemist',
                'author' => 'Paulo Coelho',
                'category' => 'Fiksi',
                'publisher' => 'HarperOne',
                'publication_year' => '1988',
                'isbn' => '9780062315007',
                'stock' => 8,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg',
                'synopsis' => 'Kisah Santiago, seorang gembala Andalusia yang bermimpi menemukan harta karun dunia.',
            ],
            [
                'title' => 'Bumi Manusia',
                'author' => 'Pramoedya Ananta Toer',
                'category' => 'Fiksi',
                'publisher' => 'Lentera Dipantara',
                'publication_year' => '1980',
                'isbn' => '9789799731234',
                'stock' => 15,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9789799731234-L.jpg',
                'synopsis' => 'Kisah Minke, pribumi cerdas yang melawan ketidakadilan kolonial Belanda.',
            ],
            [
                'title' => 'Laskar Pelangi',
                'author' => 'Andrea Hirata',
                'category' => 'Fiksi',
                'publisher' => 'Bentang Pustaka',
                'publication_year' => '2005',
                'isbn' => '9789793062792',
                'stock' => 10,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9789793062792-L.jpg',
                'synopsis' => 'Perjuangan sepuluh anak Belitong untuk terus bersekolah.',
            ],
            [
                'title' => 'Crazy Rich Asians',
                'author' => 'Kevin Kwan',
                'category' => 'Fiksi',
                'publisher' => 'Doubleday',
                'publication_year' => '2013',
                'isbn' => '9780385536974',
                'stock' => 7,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780385536974-L.jpg',
                'synopsis' => 'Komedi romantis tentang gaya hidup mewah keluarga super kaya di Singapura.',
            ],
            [
                'title' => 'Laut Bercerita',
                'author' => 'Leila S. Chudori',
                'category' => 'Fiksi',
                'publisher' => 'KPG',
                'publication_year' => '2017',
                'isbn' => '9786024246945',
                'stock' => 10,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9786024246945-L.jpg',
                'synopsis' => 'Novel sejarah tentang aktivis mahasiswa yang hilang di era Orde Baru.',
            ],
            [
                'title' => 'Cantik Itu Luka',
                'author' => 'Eka Kurniawan',
                'category' => 'Fiksi',
                'publisher' => 'Gramedia',
                'publication_year' => '2002',
                'isbn' => '9786020312583',
                'stock' => 6,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9786020312583-L.jpg',
                'synopsis' => 'Kisah magis tentang sejarah Indonesia melalui mata seorang pelacur bernama Dewi Ayu.',
            ],
            [
                'title' => 'The Hobbit',
                'author' => 'J.R.R. Tolkien',
                'category' => 'Fiksi',
                'publisher' => 'Allen & Unwin',
                'publication_year' => '1937',
                'isbn' => '9780547928227',
                'stock' => 10,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg',
                'synopsis' => 'Petualangan Bilbo Baggins mencuri harta naga.',
            ],
            [
                'title' => 'Dune',
                'author' => 'Frank Herbert',
                'category' => 'Fiksi',
                'publisher' => 'Chilton',
                'publication_year' => '1965',
                'isbn' => '9780441172719',
                'stock' => 8,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg',
                'synopsis' => 'Perang antar galaksi memperebutkan rempah-rempah di planet gurun.',
            ],
            [
                'title' => '1984',
                'author' => 'George Orwell',
                'category' => 'Fiksi',
                'publisher' => 'Secker & Warburg',
                'publication_year' => '1949',
                'isbn' => '9780451524935',
                'stock' => 12,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg',
                'synopsis' => 'Dunia distopia di bawah pengawasan Big Brother.',
            ],
            [
                'title' => 'Sherlock Holmes',
                'author' => 'Arthur Conan Doyle',
                'category' => 'Fiksi',
                'publisher' => 'George Newnes',
                'publication_year' => '1892',
                'isbn' => '9780553212419',
                'stock' => 7,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780553212419-L.jpg',
                'synopsis' => 'Petualangan detektif paling terkenal di dunia.',
            ],

            [
                'title' => 'Cosmos',
                'author' => 'Carl Sagan',
                'category' => 'Sains',
                'publisher' => 'Random House',
                'publication_year' => '1980',
                'isbn' => '9780345331359',
                'stock' => 5,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780345331359-L.jpg',
                'synopsis' => 'Perjalanan melintasi ruang dan waktu untuk memahami alam semesta.',
            ],
            [
                'title' => 'A Brief History of Time',
                'author' => 'Stephen Hawking',
                'category' => 'Sains',
                'publisher' => 'Bantam',
                'publication_year' => '1988',
                'isbn' => '9780553380163',
                'stock' => 7,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg',
                'synopsis' => 'Pembahasan kosmologi, lubang hitam, dan Big Bang.',
            ],
            [
                'title' => 'The Gene',
                'author' => 'Siddhartha Mukherjee',
                'category' => 'Sains',
                'publisher' => 'Scribner',
                'publication_year' => '2016',
                'isbn' => '9781476733500',
                'stock' => 5,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9781476733500-L.jpg',
                'synopsis' => 'Sejarah genetik manusia, dari penemuan Mendel hingga rekayasa genetika modern.',
            ],
            [
                'title' => 'Why We Sleep',
                'author' => 'Matthew Walker',
                'category' => 'Sains',
                'publisher' => 'Scribner',
                'publication_year' => '2017',
                'isbn' => '9781501144318',
                'stock' => 9,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9781501144318-L.jpg',
                'synopsis' => 'Mengungkap kekuatan tidur dan mimpi bagi kesehatan otak dan tubuh.',
            ],
            [
                'title' => 'Reality Is Not What It Seems',
                'author' => 'Carlo Rovelli',
                'category' => 'Sains',
                'publisher' => 'Riverhead Books',
                'publication_year' => '2017',
                'isbn' => '9780735213920',
                'stock' => 6,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780735213920-L.jpg',
                'synopsis' => 'Perjalanan menuju gravitasi kuantum.',
            ],
            [
                'title' => 'The Body',
                'author' => 'Bill Bryson',
                'category' => 'Sains',
                'publisher' => 'Doubleday',
                'publication_year' => '2019',
                'isbn' => '9780385539302',
                'stock' => 8,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780385539302-L.jpg',
                'synopsis' => 'Tur lengkap mengenai tubuh manusia, bagaimana fungsinya dan kemampuannya.',
            ],
            [
                'title' => 'The Selfish Gene',
                'author' => 'Richard Dawkins',
                'category' => 'Sains',
                'publisher' => 'Oxford',
                'publication_year' => '1976',
                'isbn' => '9780199291151',
                'stock' => 4,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780199291151-L.jpg',
                'synopsis' => 'Pandangan evolusi yang berpusat pada gen.',
            ],
            [
                'title' => 'Astrophysics for People in a Hurry',
                'author' => 'Neil deGrasse Tyson',
                'category' => 'Sains',
                'publisher' => 'W. W. Norton',
                'publication_year' => '2017',
                'isbn' => '9780393609394',
                'stock' => 12,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780393609394-L.jpg',
                'synopsis' => 'Panduan singkat tentang alam semesta bagi orang sibuk.',
            ],

            [
                'title' => 'Sapiens',
                'author' => 'Yuval Noah Harari',
                'category' => 'Sejarah',
                'publisher' => 'Harper',
                'publication_year' => '2011',
                'isbn' => '9780062316097',
                'stock' => 15,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg',
                'synopsis' => 'Riwayat singkat umat manusia dari zaman batu hingga abad 21.',
            ],
            [
                'title' => 'Homo Deus',
                'author' => 'Yuval Noah Harari',
                'category' => 'Sejarah',
                'publisher' => 'Harper',
                'publication_year' => '2015',
                'isbn' => '9780062464316',
                'stock' => 10,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780062464316-L.jpg',
                'synopsis' => 'Masa depan umat manusia.',
            ],
            [
                'title' => 'Guns, Germs, and Steel',
                'author' => 'Jared Diamond',
                'category' => 'Sejarah',
                'publisher' => 'W. W. Norton',
                'publication_year' => '1997',
                'isbn' => '9780393317558',
                'stock' => 6,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780393317558-L.jpg',
                'synopsis' => 'Nasib masyarakat manusia ditentukan oleh lingkungan, bukan biologi.',
            ],
            [
                'title' => 'Genghis Khan',
                'author' => 'Jack Weatherford',
                'category' => 'Sejarah',
                'publisher' => 'Crown',
                'publication_year' => '2004',
                'isbn' => '9780609610626',
                'stock' => 7,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780609610626-L.jpg',
                'synopsis' => 'Bagaimana bangsa Mongol mengubah peta politik dunia.',
            ],
            [
                'title' => '1491',
                'author' => 'Charles C. Mann',
                'category' => 'Sejarah',
                'publisher' => 'Knopf',
                'publication_year' => '2005',
                'isbn' => '9781400040063',
                'stock' => 6,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9781400040063-L.jpg',
                'synopsis' => 'Melihat kembali sejarah benua Amerika sebelum kedatangan Columbus.',
            ],
            [
                'title' => 'A Short History of Nearly Everything',
                'author' => 'Bill Bryson',
                'category' => 'Sejarah',
                'publisher' => 'Broadway Books',
                'publication_year' => '2003',
                'isbn' => '9780767908177',
                'stock' => 11,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780767908177-L.jpg',
                'synopsis' => 'Menjelaskan sejarah sains dan peradaban dengan bahasa ringan.',
            ],
            [
                'title' => 'The Diary of a Young Girl',
                'author' => 'Anne Frank',
                'category' => 'Sejarah',
                'publisher' => 'Contact Publishing',
                'publication_year' => '1947',
                'isbn' => '9780553296983',
                'stock' => 8,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780553296983-L.jpg',
                'synopsis' => 'Catatan harian memilukan dari seorang gadis yang bersembunyi selama Perang Dunia II.',
            ],
            [
                'title' => 'Sejarah Dunia yang Disembunyikan',
                'author' => 'Jonathan Black',
                'category' => 'Sejarah',
                'publisher' => 'Pustaka Alvabet',
                'publication_year' => '2007',
                'isbn' => '9789793064086',
                'stock' => 5,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9789793064086-L.jpg',
                'synopsis' => 'Membongkar sejarah dunia dari sudut pandang yang berbeda.',
            ],

            [
                'title' => 'Guinness World Records 2024',
                'author' => 'Guinness',
                'category' => 'Lainnya',
                'publisher' => 'Guinness',
                'publication_year' => '2023',
                'isbn' => '9781913484422',
                'stock' => 5,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9781913484422-L.jpg',
                'synopsis' => 'Kumpulan rekor dunia terbaru yang mencengangkan.',
            ],
            [
                'title' => 'The Art of War',
                'author' => 'Sun Tzu',
                'category' => 'Lainnya',
                'publisher' => 'Ancient China',
                'publication_year' => '-500',
                'isbn' => '9781590302255',
                'stock' => 9,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9781590302255-L.jpg',
                'synopsis' => 'Strategi militer kuno yang relevan untuk kehidupan modern.',
            ],
            [
                'title' => 'National Geographic: The Photographs',
                'author' => 'Leah Bendavid-Val',
                'category' => 'Lainnya',
                'publisher' => 'National Geographic',
                'publication_year' => '2008',
                'isbn' => '9781426202913',
                'stock' => 4,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9781426202913-L.jpg',
                'synopsis' => 'Koleksi foto terbaik yang pernah diterbitkan NatGeo.',
            ],
            [
                'title' => 'Filosofi Teras',
                'author' => 'Henry Manampiring',
                'category' => 'Lainnya',
                'publisher' => 'Kompas',
                'publication_year' => '2019',
                'isbn' => '9786024125189',
                'stock' => 10,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9786024125189-L.jpg',
                'synopsis' => 'Penerapan filsafat Stoisisme untuk mental yang tangguh masa kini.',
            ],
            [
                'title' => 'Sebuah Seni untuk Bersikap Bodo Amat',
                'author' => 'Mark Manson',
                'category' => 'Lainnya',
                'publisher' => 'Gramedia',
                'publication_year' => '2016',
                'isbn' => '9786020382210',
                'stock' => 12,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9786020382210-L.jpg',
                'synopsis' => 'Pendekatan yang waras demi menjalani hidup yang baik.',
            ],
            [
                'title' => 'Filosofi Teras: Filosofi Yunani-Romawi Kuno untuk Mental Tangguh Masa Kini',
                'author' => 'Henry Manampiring',
                'category' => 'Pengembangan Diri',
                'publisher' => 'Penerbit Buku Kompas',
                'publication_year' => '2018',
                'isbn' => '9786024125188',
                'stock' => 10,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9786024125189-L.jpg',
                'synopsis' => 'Panduan praktis untuk menerapkan filosofi Stoa dalam kehidupan modern agar mental lebih tangguh dan bahagia.',
            ],
            [
                'title' => 'Berani Tidak Disukai',
                'author' => 'Ichiro Kishimi & Fumitake Koga',
                'category' => 'Pengembangan Diri',
                'publisher' => 'Gramedia Pustaka Utama',
                'publication_year' => '2013',
                'isbn' => '9786020309996',
                'stock' => 8,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9786020309996-L.jpg',
                'synopsis' => 'Sebuah buku yang mengupas teori psikologi Alfred Adler dan bagaimana kita bisa menjadi bebas dari harapan orang lain.',
            ],
            [
                'title' => 'Man\'s Search for Meaning',
                'author' => 'Viktor Frankl',
                'category' => 'Pengembangan Diri',
                'publisher' => 'Beacon Press',
                'publication_year' => '1946',
                'isbn' => '9780807014295',
                'stock' => 7,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780807014295-L.jpg',
                'synopsis' => 'Pengalaman mengerikan Frankl di kamp konsentrasi dan teorinya tentang logoterapi.',
            ],
            [
                'title' => 'Gone Girl',
                'author' => 'Gillian Flynn',
                'category' => 'Misteri',
                'publisher' => 'Crown',
                'publication_year' => '2012',
                'isbn' => '9780307588373',
                'stock' => 10,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780307588373-L.jpg',
                'synopsis' => 'Seorang wanita menghilang pada ulang tahun pernikahannya, meninggalkan suaminya sebagai tersangka utama.',
            ],
            [
                'title' => 'The Silent Patient',
                'author' => 'Alex Michaelides',
                'category' => 'Misteri',
                'publisher' => 'Celadon Books',
                'publication_year' => '2019',
                'isbn' => '9781250301697',
                'stock' => 9,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg',
                'synopsis' => 'Seorang psikoterapis terobsesi untuk mengungkap kebenaran di balik tindakan seorang seniman terkenal yang menembak suaminya.',
            ],
            [
                'title' => 'Educated',
                'author' => 'Tara Westover',
                'category' => 'Memoir',
                'publisher' => 'Random House',
                'publication_year' => '2018',
                'isbn' => '9780399590504',
                'stock' => 11,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg',
                'synopsis' => 'Kisah nyata tentang seorang gadis yang tumbuh besar di gunung Idaho, berjuang untuk pendidikan formal.',
            ],
            [
                'title' => 'Becoming',
                'author' => 'Michelle Obama',
                'category' => 'Memoir',
                'publisher' => 'Crown',
                'publication_year' => '2018',
                'isbn' => '9781524763138',
                'stock' => 9,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9781524763138-L.jpg',
                'synopsis' => 'Memoar mantan Ibu Negara Amerika Serikat, Michelle Obama, tentang kehidupannya.',
            ],
            [
                'title' => 'The Girl with the Dragon Tattoo',
                'author' => 'Stieg Larsson',
                'category' => 'Thriller',
                'publisher' => 'Norstedts Förlag',
                'publication_year' => '2005',
                'isbn' => '9780307269751',
                'stock' => 10,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780307269751-L.jpg',
                'synopsis' => 'Seorang jurnalis dan hacker wanita misterius menyelidiki hilangnya seorang wanita muda dari keluarga kaya.',
            ],
            [
                'title' => 'The Midnight Library',
                'author' => 'Matt Haig',
                'category' => 'Fiksi Kontemporer',
                'publisher' => 'Canongate Books',
                'publication_year' => '2020',
                'isbn' => '9780525559474',
                'stock' => 13,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg',
                'synopsis' => 'Nora Seed, di ambang kematian, mendapat kesempatan untuk mencoba kehidupan lain yang bisa dia jalani.',
            ],
            [
                'title' => 'Where the Crawdads Sing',
                'author' => 'Delia Owens',
                'category' => 'Fiksi Sastra',
                'publisher' => 'G.P. Putnam\'s Sons',
                'publication_year' => '2018',
                'isbn' => '9780735219090',
                'stock' => 14,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780735219090-L.jpg',
                'synopsis' => 'Kisah seorang gadis muda yang tumbuh di rawa-rawa Carolina Utara, menjadi tersangka pembunuhan.',
            ],
            [
                'title' => 'Project Hail Mary',
                'author' => 'Andy Weir',
                'category' => 'Fiksi Ilmiah',
                'publisher' => 'Ballantine Books',
                'publication_year' => '2021',
                'isbn' => '9780593135204',
                'stock' => 12,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg',
                'synopsis' => 'Seorang guru sekolah terbangun di luar angkasa dengan misi menyelamatkan umat manusia, tetapi tanpa ingatan.',
            ],
            [
                'title' => 'Dunia Sophie',
                'author' => 'Jostein Gaarder',
                'category' => 'Filosofi',
                'publisher' => 'Aschehoug',
                'publication_year' => '1991',
                'isbn' => '9789794332213',
                'stock' => 8,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9789794332213-L.jpg',
                'synopsis' => 'Perjalanan Sophie Amundsen belajar filosofi dari seorang guru misterius.',
            ],
            [
                'title' => 'Cantik Itu Luka',
                'author' => 'Eka Kurniawan',
                'category' => 'Fiksi',
                'publisher' => 'Gramedia Pustaka Utama',
                'publication_year' => '2002',
                'isbn' => '9789792284411', // Modified ISBN
                'stock' => 6,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9789792284411-L.jpg',
                'synopsis' => 'Kisah magis dan gelap tentang sejarah Indonesia melalui mata seorang pelacur bernama Dewi Ayu.',
            ],
            [
                'title' => 'Milea: Suara dari Dilan',
                'author' => 'Pidi Baiq',
                'category' => 'Romance',
                'publisher' => 'Pastel Books',
                'publication_year' => '2016',
                'isbn' => '9786027870902',
                'stock' => 15,
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9786027870902-L.jpg',
                'synopsis' => 'Kisah cinta Dilan dan Milea diceritakan dari sudut pandang Dilan.',
            ],
        ];

        $books = array_map(function ($book) {
            $book['total_pages'] = rand(100, 500);
            return $book;
        }, $books);

        foreach ($books as $book) {
            Book::create($book);
        }
    }
}
